// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueryUserClient is the client API for QueryUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryUserClient interface {
	GetUserInfo(ctx context.Context, in *ReqParam, opts ...grpc.CallOption) (*ResParam, error)
}

type queryUserClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryUserClient(cc grpc.ClientConnInterface) QueryUserClient {
	return &queryUserClient{cc}
}

func (c *queryUserClient) GetUserInfo(ctx context.Context, in *ReqParam, opts ...grpc.CallOption) (*ResParam, error) {
	out := new(ResParam)
	err := c.cc.Invoke(ctx, "/service.QueryUser/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryUserServer is the server API for QueryUser service.
// All implementations must embed UnimplementedQueryUserServer
// for forward compatibility
type QueryUserServer interface {
	GetUserInfo(context.Context, *ReqParam) (*ResParam, error)
	mustEmbedUnimplementedQueryUserServer()
}

// UnimplementedQueryUserServer must be embedded to have forward compatible implementations.
type UnimplementedQueryUserServer struct {
}

func (UnimplementedQueryUserServer) GetUserInfo(context.Context, *ReqParam) (*ResParam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedQueryUserServer) mustEmbedUnimplementedQueryUserServer() {}

// UnsafeQueryUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryUserServer will
// result in compilation errors.
type UnsafeQueryUserServer interface {
	mustEmbedUnimplementedQueryUserServer()
}

func RegisterQueryUserServer(s grpc.ServiceRegistrar, srv QueryUserServer) {
	s.RegisterService(&QueryUser_ServiceDesc, srv)
}

func _QueryUser_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryUserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.QueryUser/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryUserServer).GetUserInfo(ctx, req.(*ReqParam))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryUser_ServiceDesc is the grpc.ServiceDesc for QueryUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.QueryUser",
	HandlerType: (*QueryUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _QueryUser_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
